
#' Create a daily sequence of stand properties (lai, sai, height, age)
#'
#' Uses a table with yearly values of perennial vegetation development or anually constant
#' values (maxlai, minlai, sai, height, age) and turns them into a daily table of vegetation
#' properties, that can be passed on to write.climate.in
#' @param stand.years A sequence of years or a single year, at which the stand properties were measured
#' @param maxlai Maximum leaf area index during summer, either a fixed single value or
#' corresponding to stand.years
#' @param minlai Minimum leaf area index during winter, either a fixed single value or
#' corresponding to stand.years.
#' @param budburst.doy Day of year when leaf flushing sets in, either a fixed single
#' value or corresponding to stand.years.
#' @param leaffall.doy Day of year when leaffall begins, either a fixed single value
#' or corresponding to stand.years.
#' @param sai Stem area index, either a fixed single value or corresponding to
#' stand.years.
#' @param height Vegetation height, either a fixed single value or corresponding
#' to stand.years. m
#' @param densef Relative vegetation density values, either a fixed single
#' value orcorresponding to stand.years.
#' @param age Vegetation age, internally used in LWF-Brook90 for root growth (see parameters
#' rgrorate, rgroper,inirtlen, inirdep). Either a fixed single value or corresponding
#' to the beginning of stand.years, or corresponding to stand.years. a
#' @param yearsout years for which ouput is generated, maybe longer or shorter than
#' stand.years,but must include at least one of the values in stand.year.
#' @param ... parameters passed to \code{\link{MakeSeasLAI}}.
#'
#' @return Returns a data.frame with columns lai, sai, height,
#' densef at daily resolution
#'
#' @details Linear interpolation is used to  generate daily sequences from yearly values of
#' sai, height, densef and age. Daily leaf area index is generated by \code{\link{MakeSeasLAI}}.
#'
#' @export
MakeStand <- function(stand.years,
                      maxlai,
                      minlai,
                      budburst.doy,
                      leaffall.doy,
                      sai,
                      height,
                      densef,
                      age,
                      yearsout = stand.years,
                      ... #parameters passed to function MakeSeasLAI
){

  # data
  longterm.stand.dyn <- data.frame(year = stand.years, maxlai, minlai, sai,
                                   height, densef, age)

  #in case only constant parameters are given
  if (nrow(longterm.stand.dyn) == 1) {
    longterm.stand.dyn <- longterm.stand.dyn[rep(1,length(yearsout)),]
    #recalculate age
    longterm.stand.dyn$age <-  seq(from = min(age) - (min(stand.years) - min(yearsout)),
                                   by = 1, length.out = nrow(longterm.stand.dyn))
    longterm.stand.dyn$year <- yearsout
  }

  #if necessary prolongate or constrain standdata to yearsout
  #beginning
  if (min(stand.years) > min(yearsout)) {
    longterm.stand.dyn <- rbind(
      longterm.stand.dyn[rep(1,min(longterm.stand.dyn$year) - min(yearsout)),],
      longterm.stand.dyn)
  } else {
    longterm.stand.dyn <- longterm.stand.dyn[which(longterm.stand.dyn$year >= min(yearsout)),]
  }
  #end
  if (max(stand.years) < max(yearsout)) {
    longterm.stand.dyn <- rbind(
      longterm.stand.dyn,
      longterm.stand.dyn[rep(nrow(longterm.stand.dyn),max(yearsout) - max(longterm.stand.dyn$year)),])
  } else {
    longterm.stand.dyn <- longterm.stand.dyn[which(longterm.stand.dyn$year <= max(yearsout)),]
  }

  if (length(unique(longterm.stand.dyn$year)) < length(yearsout)) {
    #recalculate year and age
    longterm.stand.dyn$year <- yearsout #recalculate
    longterm.stand.dyn$age <-  seq(from = min(age) - (min(stand.years) - min(yearsout)),
                                   by = 1, length.out = nrow(longterm.stand.dyn))
  }

  longterm.stand.dyn$datum <- as.Date(paste(longterm.stand.dyn$year,"-01-01",sep = ""), "%Y-%m-%d")
  longterm.stand.dyn$maxdoy <- with(longterm.stand.dyn,
                                    ifelse( ((year %% 4 == 0) & (year %% 100 != 0)) | (year %% 400 == 0),
                                            366, 365) )

  for (i in 1:nrow(longterm.stand.dyn)) {

    TempLAI <- with(longterm.stand.dyn,
                    MakeSeasLAI(maxdoy = maxdoy[i],
                                minlai = minlai[i],
                                maxlai = maxlai[i],
                                budburst.doy = budburst.doy[i],
                                leaffall.doy = leaffall.doy[i],
                                ...)
    )


    if (i == 1) {
      LAI <- TempLAI
    } else {LAI <- c(LAI, TempLAI)}
  }

  ########
  # interpolate some stand characteristics (applies also to "constant" mode)
  #helper for extrapolation
  #ToDo: Make height growth depending on growing season!
  expol <- longterm.stand.dyn[nrow(longterm.stand.dyn),
                              c("year","age","height","sai","densef")]
  expol[,c("age","year")] <- expol[,c("age","year")] + 1
  expol$datum <- as.Date(paste(expol$year,"-01-01",sep = ""), "%Y-%m-%d")

  # make output
  out <- data.frame(dates = seq.Date(from = as.Date(paste0(min(yearsout),"-01-01")),
                                     to = as.Date(paste0(max(yearsout),"-12-31")),
                                     by = "day"))

  out$height <- approx(c(longterm.stand.dyn$datum, expol$datum),
                             c(longterm.stand.dyn$height,expol$height),
                             rule = 2, method = "linear",
                             xout = out$dates)$y

  out$sai <-   approx(c(longterm.stand.dyn$datum,expol$datum),
                      c(longterm.stand.dyn$sai,expol$sai),
                      rule = 2, method = "linear",
                      xout = out$dates)$y

  out$age <- approx(c(longterm.stand.dyn$datum,expol$datum),
                    c(longterm.stand.dyn$age,expol$age),
                    rule = 2, method = "linear",
                    xout = out$dates)$y

  out$densef <- approx(c(longterm.stand.dyn$datum,expol$datum),
                                  c(longterm.stand.dyn$densef,expol$densef),
                                  rule = 2, method = "linear",
                                  xout = out$dates)$y

  out$lai <- LAI

  return(out)
}
