#' Create a daily sequence of stand properties (lai, sai, height, age)
#'
#' Uses a table with yearly values of perennial vegetation development or anually constant
#' values (maxlai, winlaifrac, sai, height, age) and turns them into a daily table of vegetation
#' properties, that can be passed on to write.climate.in
#' @param stand.years A sequence of years or a single year, at which the stand properties were measured
#' @param maxlai Maximum leaf area index during summer, either a fixed single value or
#' corresponding to stand.years
#' @param winlaifrac Minimum leaf area index during winter, either a fixed single value or
#' corresponding to stand.years.
#' @param budburst.doy Day of year when leaf flushing sets in, either a fixed single
#' value or corresponding to stand.years.
#' @param leaffall.doy Day of year when leaffall begins, either a fixed single value
#' or corresponding to stand.years.
#' @param sai Stem area index, either a fixed single value or corresponding to
#' stand.years.
#' @param height Vegetation height, either a fixed single value or corresponding
#' to stand.years. m
#' @param densef Relative vegetation density values, either a fixed single
#' value orcorresponding to stand.years.
#' @param age Vegetation age, internally used in LWF-Brook90 for root growth (see parameters
#' rgrorate, rgroper,inirtlen, inirdep). Either a fixed single value or corresponding
#' to the beginning of stand.years, or corresponding to stand.years. a
#' @param years.out years for which ouput is generated, maybe longer or shorter than
#' stand.years,but must include at least one of the values in stand.year.
#' @param ... parameters passed to \code{\link{MakeSeasLAI}}.
#'
#' @return Returns a data.frame with columns lai, sai, height,
#' densef at daily resolution
#'
#' @details Linear interpolation is used to  generate daily sequences from yearly values of
#' sai, height, densef and age. Daily leaf area index is generated by \code{\link{MakeSeasLAI}}.
#'
#' @export
MakeStand <- function(stand.years,
                      sai,
                      height,
                      densef,
                      age,
                      years.out = stand.years,
                      approx.method){

  #TODO: Properties are currently interpolated with the values interpreted as valid
  # for the 1st of January of the respective years of the simulation. Between these dates,
  # values are interpolated to daily values and extrapolated to for the last year,
  # using the increment of the year before. It would be nicer to let growth of sai
  # and height take place only during the growing season, and also provide inital
  # values height and sai by parameters.


  # data
  longterm.stand.dyn <- data.frame(year = stand.years, height, sai, densef, age)

  #if necessary prolongate standproperties to years.out (only happens if longtermdev-table is supplied)
  #beginning
  if (min(stand.years) > min(years.out)) {
    longterm.stand.dyn <- rbind(
      longterm.stand.dyn[rep(1,min(longterm.stand.dyn$year) - min(years.out)),],
      longterm.stand.dyn)
  }
  #end
  if (max(stand.years) < max(years.out)) {
    longterm.stand.dyn <- rbind(
      longterm.stand.dyn,
      longterm.stand.dyn[rep(nrow(longterm.stand.dyn),max(years.out) - max(longterm.stand.dyn$year)),])
  }

  if (length(unique(longterm.stand.dyn$year)) < length(years.out)) {
    #recalculate year and age (if period was prolonged)
    longterm.stand.dyn$year <- years.out
    longterm.stand.dyn$age <-  seq(from = min(age) - (min(stand.years) - min(years.out)),
                                   by = 1, length.out = nrow(longterm.stand.dyn))
  }

  longterm.stand.dyn$datum <- as.Date(paste(longterm.stand.dyn$year,"-01-01",sep = ""), "%Y-%m-%d")

  ########
  # interpolate and extrapolate stand characteristics

  # make output
  out <- data.frame(dates = seq.Date(from = as.Date(paste0(min(years.out),"-01-01")),
                                     to = as.Date(paste0(max(years.out),"-12-31")),
                                     by = "day"))

  out$height <- approx(longterm.stand.dyn$datum,
                       longterm.stand.dyn$height,
                       rule = 2, f = 0,
                       method = approx.method,
                       xout = out$dates)$y

  out$sai <-   approx(longterm.stand.dyn$datum,
                      longterm.stand.dyn$sai,
                      rule = 2, f = 0,
                      method = approx.method,
                      xout = out$dates)$y

  out$densef <- approx(longterm.stand.dyn$datum,
                       longterm.stand.dyn$densef,
                       rule = 2, f = 0,
                       method = approx.method,
                       xout = out$dates)$y

  out$age <- approx(longterm.stand.dyn$datum,
                    longterm.stand.dyn$age,
                    rule = 2, method = "linear",
                    xout = out$dates)$y


  return(out)
}
